export const SET_AUTHORIZED_USER = "SET_AUTHORIZED_USER";
export const GET_QUESTIONS = "GET_QUESTIONS";
export const ADD_ANSWER_TO_QUESTION = "ADD_ANSWER_TO_QUESTION";
export const ADD_QUESTION = "ADD_QUESTION";
export const GET_USERS = "GET_USERS";
export const ADD_ANSWER_TO_USER = "ADD_ANSWER_TO_USER";
export const QUESTION_ADDITION_TO_USER = "QUESTION_ADDITION_TO_USER";
export const PollContentType = {
  ALTERNATE: "ALTERNATE",
  QUESTION: "QUESTION",
  RESULT: "RESULT",
};
